print('==========================')
x = input(' Digite algo: ')
print('==========================')
print(' O tipo primitivo é', type(x))
print(' É um número?', x.isnumeric())
print(' É um texto ou alfabético? ', x.isalpha())
print(' É um texto em maiúsculo?', x.isupper())
print(' É em texto em minúsculo?', x.islower())
print(' É um número decimal?', x.isdecimal())
print(' É alfanumérico?', x.isalnum())
print(' É vazio?', x.isspace())
print(' Está capitalizada?', x.istitle())
